# docker-compose.yml

version: "3.7"
networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c log_statement=all
    ports: 
      - '5432:5432'
    volumes:
      - library-db:/var/lib/postgresql/data
    networks:
      - app-tier      

  zipkin:
    image: openzipkin/zipkin
    ports: 
      - 9411:9411
    networks:
      - app-tier      

  library:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    command: "node --inspect-brk=0.0.0.0 --require './tracing.js' ./bin/www"
    depends_on:
      - postgres
      - zipkin
    ports:
      - '3000:3000'
      - '9229:9229'  #open for debug.
    networks:
      - app-tier      

volumes:
  library-db: