# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  bookservice:
    if: github.event.client_payload.job == 'bookservice'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - working-directory: ./bookservice
      - run: npm ci
      - run: npm test
      
  checkout:
    if: github.event.client_payload.job == 'checkout'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - working-directory: ./checkout
      - run: npm ci
      - run: npm test
